server:
  port: 9006

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: @eureka.host@
    #eureka client刷新本地缓存时间 默认30s
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除 默认90s
    lease-expiration-duration-in-seconds: 9
    #服务刷新时间配置，每隔这个时间会主动心跳一次 默认30s
    lease-renewal-interval-in-seconds: 3
    non-secure-port: ${server.port}
    #健康检查路径
    health-check-url-path: /actuator/health

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        # 本地存储
        # native:
        #  search-locations: classpath:/shared
        git:
          uri: @config.git.url@ #配置git服务地址
          username: @config.git.username@ #配置git用户名
          password: @config.git.password@ #配置git密码
          search-paths:
          - edu-ad-boot
          - edu-authority-boot
          - edu-boss-boot
          - edu-comment-boot
          - edu-course-boot
          - edu-front-boot
          - edu-gateway-boot
          - edu-message-boot
          - edu-oauth-boot
          - edu-order-boot
          - edu-pay-boot
          - edu-user-boot
          default-label: master # 使用的默认分支，默认为 master
          basedir: @config.git.basedir@
          clone-on-start: true
      # 读取分支
      label: master
  rabbitmq:
    host: @mq.host@
    port: @mq.port@
    username: @mq.username@
    password: @mq.password@
  main:
    allow-bean-definition-overriding: true

# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always